language: go

# Be explicit about not needing sudo, so that Travis will use container-based
# infrastructure for our jobs, always, fewer heuristics.
sudo: false

go:
  - 1.19.x
# 2016-03-14: removed `tip` ∵ `go vet` on Travis throwing false errors,
# complaining about missing format strings where they're most definitely
# present.
# 2020-02-05: removed prior-to-1.13, because of changes in rune display width
# calculations and the values we're trying to assert depending upon Go version

script:
  - ./util/show_versions.sh
  - go build
  - go vet ./...
  - go test ./...

# vim: set sw=2 et :
