#!/bin/sh -eu

# This should not be in shell, should move to go, but for now, be fast to write

# Places seen for HTML data:
#   /usr/local/share/sgml/html/4.01
#   /opt/local/share/OpenSP
# debian/ubuntu: sgml-data => /usr/share/sgml/html/entities

# Places seen for XML data:
#   /usr/local/share/xml/xmlcharent
#   reverse glob /opt/local/share/xml/docbook/*/ent
# debian/ubuntu: sgml-data => /usr/share/xml/entities/xml-iso-entities-8879.1986
# homebrew: docbook => /usr/local/Cellar/docbook/$VERSION/docbook/xml/{$versions_list}/ent dirs

# Also: sgml-data gives us /usr/share/sgml/entities/sgml-iso-entities-${versions_list}/ dirs

echo >&2 "$0: NOT IMPLEMENTED"
exit 0
